### ISSUE TITLE
Get typeof parent in factory

### ISSUE THREAD

**Issue by trampster** [YairHalberstadt/stronginject#117]
We use serilog for logging and it needs to be initialised with the type of the object it will be logging for (the type it is injected into)

ILogger specificLogger = logger.ForContext(typeof(Parent))

Our types have the ILogger as constructor arguments and out current injection framework creates them for us with the correct context.

I can't see anyway to achieve this with stronginject Factories

**Comment by YairHalberstadt** [comment]
Currently stronginject have no knowledge of why they're being resolved. I would like to provide a solution to this, but it is not a priority at the moment.

In the meantime, I would suggest using Microsoft.Extensions.Logging.ILogger<T>.  Their logger takes a type parameter to mark the type it's used for, which allows easy resolution. I'm sure there is an implementation of this interface for Serilog. 

I know changing everything may not be practical. I will try to think of a way to intercept a resolution and inject some extra information.

**Comment by YairHalberstadt** [comment]
I have proposed a design at https://github.com/YairHalberstadt/stronginject/issues/109#issuecomment-883068923. Please take a look and let me know what you think! Thanks!

**Comment by YairHalberstadt** [comment]
CLosing as duplicate of #109
