### ISSUE TITLE
Warning Resolving all registration of type 'object', but there are no such registrations

### ISSUE THREAD

**Issue by trampster** [YairHalberstadt/stronginject#121]
I'm getting this as a warning, but I don't know what it means or why I am getting it, as far as I can tell I don't have any constructors taking object.

**Comment by YairHalberstadt** [comment]
You're getting this if you're resolving an array of objects, but you've never registered anything as an object.

**Comment by trampster** [comment]
I don't seem to have any arrays of object.

I do have a IHardwareButtonProvider[] but I have a Factory defined for that.

```
[Factory]
public static IHardwareButtonProvider[] CreateHardwareProvider(RugGearButtonProvider rugGearButtonProvider, SonimButtonProvider sonimButtonProvider)
{
    return new IHardwareButtonProvider[]
    {
        rugGearButtonProvider,
        sonimButtonProvider
    };
}
```

Both RugGearButtonProvider and SonimButtonProvider are registered as SingleInstance

**Comment by trampster** [comment]
I discovered that I did have a dependency on a array of object (defined using param object[]) so it was hard to see in my existing IoC.
