### ISSUE TITLE
Preview packages go backwards in version from released packages

### ISSUE THREAD

**Issue by jnm2** [YairHalberstadt/stronginject#137]
This led me to believe visually that there was no preview in this feed. It also confuses NuGet tooling when you ask for prerelease updates.

Ordinarily, the version would be `1.2.1-x`. I use a build script that autoincrements the csproj/props version based on git tags so that manual commits are not needed to achieve this. (https://github.com/Techsola/InstantReplay/blob/main/build.ps1#L17-L20)

![image](https://user-images.githubusercontent.com/8040367/128355864-957ce0ca-7fe2-4a2b-a2d9-67032f29026c.png)

**Comment by YairHalberstadt** [comment]
Oops, usually I manually upgrade minor after each release, but forgot to this time.
