### ISSUE TITLE
[Feature/Idea] Support for primary constructor generator

### ISSUE THREAD

**Issue by szekelymatyas** [YairHalberstadt/stronginject#141]
I really like the concept of PrimaryConstructor and StrongInject. It is obvious that the generation process of StrongInject does not see the generated constructor by PrimaryConstructor.

Here is the git repository for PrimaryConstructor:  https://github.com/chaowlert/PrimaryConstructor

I think PrimaryContructor is a fantastic source generator to remove some boilerplate codes, and it would be nice to use them together.

**Comment by YairHalberstadt** [comment]
Unfortunately at the moment source generators can't see other source generators. I opened an issue to work around this at https://github.com/dotnet/roslyn/discussions/48358.

**Comment by YairHalberstadt** [comment]
Closing as there's nothing I can do about this. It's up to the Roslyn team. Thanks for your suggestion though!
