### ISSUE TITLE
Circular dependency check is too restrictive for delegates

### ISSUE THREAD

**Issue by jnm2** [YairHalberstadt/stronginject#162]
Creating a new instance this way is necessary. SomeViewModel can't call its own constructor because the lifetimes of the view models will be completely independent of each other, and each needs separate instances of transient dependencies.

(This implements "New" and "Duplicate" buttons which open new tabs, exactly the way it would be done if the new tab needed to contain a different view model.)

```cs
using StrongInject;
using System;

[Register(typeof(SomeViewModel))]
// ❌ SI0101 Error while resolving dependencies for 'SomeViewModel': 'SomeViewModel' has a circular dependency
public sealed partial class Container : IContainer<SomeViewModel>
{
}

public sealed class SomeViewModel
{
    // Would be Func<Owned<SomeViewModel>>, but this simplifies the repro
    public SomeViewModel(Func<SomeViewModel> someViewModelFactory) { }
}
```

Willing to implement. Also, I can't think of a way to move to StrongInject so long as this restriction is in place.

**Comment by YairHalberstadt** [comment]
I think one level that would be safe to carve out is a delegate that depends on itself directly or indirectly without going through any intermediate delegates. I'm not 100% sure about this - will have to think through possible counterexamples.

**Comment by jnm2** [comment]
These are the two scenarios I can foresee wanting.

```cs
class A
{
    public delegate Owned<A> Factory(int aId);

    public A(int aId, A.Factory aFactory) { }
}
```

And:
```cs
class A
{
    public delegate Owned<A> Factory(int aId);

    public A(int aId, B.Factory bFactory) { }
}

class B
{
    public delegate Owned<B> Factory(int bId);

    public B(int bId, A.Factory aFactory) { }
}
```

**Comment by YairHalberstadt** [comment]
I think we can do that:

We allow delegate recursion if and only if the set of delegate parameters that are in scope to the recursed object are the same as to the original object.

So resolving B is allowed here:

```csharp
record A(Func<int, B> func);
record B(Func<int, A> func);
```

Since the inner `Func<int, A>` overrides the `int` that `Func<int, B>` provides with it's own, so it has exactly the same objects available for it to use as the outer `Func<int, A>`.

But this wouldn't be:

```csharp
record A(Func<string, B> func);
record B(Func<int, A> func);
```

Since the inner `Func<int, A>` has access to the `string` that `Func<string, B>` provides, and the outer `Func<int, A>` doesn't, so we can't reuse the outer `Func<int, A>` as a dependency to `Func<string, B>`.

**Comment by jnm2** [comment]
Oh no, then I left out something important. Instead of `int aId` and `int bId`, often it is different types.

In all cases it would never make sense to use the delegate parameters used to obtain `A` to later obtain `B` or vice versa.

**Comment by YairHalberstadt** [comment]
The problem with that case is due to the recursive nature of what's going on, it's incredibly tricky to prove that the inner func will never use the string.

**Comment by jnm2** [comment]
Does there have to be an inner func?
It would be interesting to know what the use case would be for letting delegate parameters be used for anything other than directly passing to the constructor of the type used as the delegate return type.

**Comment by jnm2** [comment]
Let's put it this way: it would be a bad surprise to find out that the `getB` delegate parameter was used to construct A if `getA` was called:

```cs
[Register(typeof(A))]
[Register(typeof(B))]
[Register(typeof(C))]
partial class Container : IContainer<A>, IContainer<B>
{
}

record A(C c, Func<C, B> getB);
record B(C c, Func<A> getA);
```

**Comment by YairHalberstadt** [comment]
Why would it be a bad surprise?

I always found the fact this didn't work to be an extremely annoying feature of AutoFac

**Comment by jnm2** [comment]
In all the cases where this appears, we're using it as navigation between view models (pages) with no sharing of lifetimes or dependencies between A and B.

**Comment by jnm2** [comment]
So how do you escape this behavior if you don't like it? A new attribute placed somewhere?

Maybe it's possible to do the hard proof required by the current viral nature of delegate parameter values so that this question can be avoided.

**Comment by jnm2** [comment]
In fact, you could opt *in* to the desired behavior by changing `Func<A> CreateA` to `Func<C, A> CreateA` and explicitly flowing the value, but you can currently never opt *out*.

**Comment by jnm2** [comment]
Imagining some new attribute used to configure this per container, I'm thinking that it would still be beneficial to carve something out so that you can still do at least the `record A(Foo Foo, Func<Foo, A> AFactory);` case. That makes me think that we can avoid the whole question for now of whether delegate parameter values should be viral.

**Comment by YairHalberstadt** [comment]
I definitely plan to carve out some percentage of this and do that.

As for why I think it's important that these things be viral.

Take a typical use case for Funcs with parameters:

```csharp
public class RequestHandler(Func<Credentials, Owned<FrobEngine>> factory)
{
    public void OnRequest(Credentials creds) 
    {
        using var owned = factory(creds);
        owned.Value.Frob();
    }
}
```

This works absolutely fine if FrobEngine looks like this:

```csharp
public class FrobEngine(Credentials creds);
```

but what if it's like this?

```csharp
public class FrobEngine(IAuthenticationService authService);
public class AuthenticationService(Credentials creds) : IAuthenticationService;
```

If you're in Autofac non-viral land, everything breaks. You've now got to basically register your own delegate to create FrobEngine from a Credentials. But the whole point of an IOC container is that in general I shouldn't have to instantiate things myself.

In StrongInject, where delegate params are viral, everything just works as expected. Each delegate creates a new scope, where you've effectively registered whatever the delegate parameter is and can use it normally.

This is already used in [FluentLang](https://github.com/YairHalberstadt/fluentlang/blob/f84e8ce4a0eafe4401ae0fe80f5d72573067564e/source/flc/FluentLangCompiler.cs#L35) where ProjectLoader doesn't directly use SolutionInfo, but FileAsemblyLoader, one of it's indirect dependencies, does.

**Comment by jnm2** [comment]
Okay, that's a great demo of why it's useful to pass delegate arguments to constructors other than the exact type that is the delegate return type. And this also doesn't trigger my "spooky action" suspicion.

Now I'm considering if it's useful to let these flow through a different delegate. Imagine that `FrobEngine` took `Func<IAuthenticationService>` instead. Then, it's suddenly much easier to do without the viral values from the original delegate parameter; FrobEngine just needs a `Credentials` parameter and a `Func<Credentials, IAuthenticationService>` parameter.

**Comment by YairHalberstadt** [comment]
> Now I'm considering if it's useful to let these flow through a different delegate. Imagine that FrobEngine took Func<IAuthenticationService> instead. Then, it's suddenly much easier to do without the viral values from the original delegate parameter; FrobEngine just needs a Credentials parameter and a Func<Credentials, IAuthenticationService> parameter. At least some of the time, it will already have a Credentials-like parameter.

I'm not really seeing the difference here. FrobEngine shouldn't have to now that the implementation of `IAuthenticationService` takes a `Credentials`. Theoretically, I may not control `FrobEngine` at all.

That said, I think it's worth considering making this an exception anyway, not because it' particularly logical, but because it opens up the ability to support recursive functions.

So here's the options as I see them:

1. Only allow recursive functions where we know it can't close over any delegate parameters. Easily achievable, but only solves a subset of cases.
2. Only allow recursive functions which happen not to close over any delegate parameters. May be extremely complex.
3. Allow all recursive functions, but when a function is recursive it will not close over delegate parameters as you might expect, even though functions usually do. Easily achievable, but may lead to surprising behavior.
4. Disallow any functions from closing over any delegate parameters ever. Easily achievable but both a breaking change, and also disallows other behavior which we want to enable. I'm not too worried about the breaking change since StrongInject is not super widely used right now and this is relatively niche. If we had to allow only one or the other, I'm not sure which is more useful.

**Comment by jnm2** [comment]
Would a modified version of 3 work, where we stop nesting delegates inside other delegates whenever possible, completely ignoring (at this stage) whether a cycle exists in the graph of all things?

**Comment by YairHalberstadt** [comment]
@jnm2 I'm not sure I understand?

**Comment by jnm2** [comment]
What I was trying to get at, is there a difference if we see it the other way around and say that the default is to not nest delegates, but we do so if forced to by the fact that a delegate parameter could possibly be captured? I guess that's the same as 2 actually.

**Comment by YairHalberstadt** [comment]
I think that is the same as 2, yes.

**Comment by jnm2** [comment]
Maybe if we do 1, it will be a long time before the mutually recursive situation comes up.

I tried the workaround in https://github.com/YairHalberstadt/stronginject/issues/162#issuecomment-950282660 and it didn't make any difference to the circular dependency warning, except that it showed up only once per `IContainer<X>` implementation on the same class rather than seven times per implementation.

**Comment by jnm2** [comment]
Using the power of `Func<Owned<>>`, I was able to create a 69-line monstrosity that works perfectly as a workaround. This form looks like it would work automatically for mutual recursion as well.

```cs
// Workaround for https://github.com/YairHalberstadt/stronginject/issues/162
[Factory(Scope.SingleInstance)]
public static Func<SomeParameter, Owned<SomeViewModel>> GetSomeViewModelFactory(
    Func<Owned<DependencyA>> dependencyA,
    Func<Owned<DependencyB>> dependencyB,
    Func<Owned<DependencyC>> dependencyC,
    Func<Owned<DependencyD>> dependencyD,
    Func<Owned<DependencyE>> dependencyE,
    Func<Owned<DependencyF>> dependencyF,
    Func<Owned<DependencyG>> dependencyG,
    Func<Owned<DependencyH>> dependencyH,
    Func<Owned<DependencyI>> dependencyI,
    Func<Owned<DependencyJ>> dependencyJ,
    Func<Owned<DependencyK>> dependencyK)
{
    return someParameter =>
    {
        var ownedDependencyA = dependencyA.Invoke();
        var ownedDependencyB = dependencyB.Invoke();
        var ownedDependencyC = dependencyC.Invoke();
        var ownedDependencyD = dependencyD.Invoke();
        var ownedDependencyE = dependencyE.Invoke();
        var ownedDependencyF = dependencyF.Invoke();
        var ownedDependencyG = dependencyG.Invoke();
        var ownedDependencyH = dependencyH.Invoke();
        var ownedDependencyI = dependencyI.Invoke();
        var ownedDependencyJ = dependencyJ.Invoke();
        var ownedDependencyK = dependencyK.Invoke();

        var instance = new SomeViewModel(
            someParameter,
            ownedDependencyA.Value,
            ownedDependencyB.Value,
            ownedDependencyC.Value,
            GetSomeViewModelFactory(
                dependencyA,
                dependencyB,
                dependencyC,
                dependencyD,
                dependencyE,
                dependencyF,
                dependencyG,
                dependencyH,
                dependencyI,
                dependencyJ,
                dependencyK),
            ownedDependencyD.Value,
            ownedDependencyE.Value,
            ownedDependencyF.Value,
            ownedDependencyG.Value,
            ownedDependencyH.Value,
            ownedDependencyI.Value,
            ownedDependencyJ.Value,
            ownedDependencyK.Value);

        return new Owned<SomeViewModel>(instance, () =>
        {
            ownedDependencyA.Dispose();
            ownedDependencyB.Dispose();
            ownedDependencyC.Dispose();
            ownedDependencyD.Dispose();
            ownedDependencyE.Dispose();
            ownedDependencyF.Dispose();
            ownedDependencyG.Dispose();
            ownedDependencyH.Dispose();
            ownedDependencyI.Dispose();
            ownedDependencyJ.Dispose();
            ownedDependencyK.Dispose();
        });
    };
}
```
