### ISSUE TITLE
Separate Microsoft DI from Asp.Net Core

### ISSUE THREAD

**Issue by KuraiAndras** [YairHalberstadt/stronginject#176]
The code which uses `IServiceCollection` should be separated from Asp.Net Core. When you use StrongInject in places which already uses `IServiceProvider` and the whole `GenericHost` you might not want to have a dependency on Asp.Net Core. I would like to try StrongInject with Unity, using my DI extension [Injecter](https://github.com/KuraiAndras/Injecter/), and having a dependency on Asp.Net core is a no-go. It might also be undesirable for Maui, WinUI, WPF, Avalonia or any other type of poject.

**Comment by KuraiAndras** [comment]
fixed by #177

**Comment by YairHalberstadt** [comment]
available in release 1.4.2
