### ISSUE TITLE
Confusing use of the term 'delegate parameters' in the readme

### ISSUE THREAD

**Issue by jnm2** [YairHalberstadt/stronginject#190]
<https://github.com/YairHalberstadt/stronginject#decorators>:

> Instances provided by [delegate parameters](https://github.com/YairHalberstadt/stronginject#delegate-support) are never decorated.

If I understand what it's saying, I'm relieved that it's incorrect. It would be a very unpleasant pit of failure to switch from injecting `B` to `Func<B>` and start getting a different instance.

Demonstrating (using 1.4.4) an instance provided by a delegate parameter being decorated:

```cs
using System;
using StrongInject;

using var container = new Container();

container.Run(a =>
{
    a.FuncOfB(); // Prints: Decorated B!
});

[Register(typeof(A)), Register(typeof(B))]
partial class Container : IContainer<A>
{
    [DecoratorFactory]
    private static B Test(B b)
    {
        Console.WriteLine("Decorated B!");
        return b;
    }
}

record A(Func<B> FuncOfB);
record B;
```

**Comment by YairHalberstadt** [comment]
That's a delegate return type, not a delegate parameter...

**Comment by jnm2** [comment]
Ah, I got it now from chatting on Discord. I'm thinking of something like "When an injected delegate is invoked with arguments, the arguments to the delegate are not decorated. The return value from the delegate is decorated." And maybe an example.
