### ISSUE TITLE
Support resolving all registrations for a type.

### ISSUE THREAD

**Issue by YairHalberstadt** [YairHalberstadt/stronginject#37]
This would allow resolving `IEnumerable<T>` for example.

Currently StrongInject doesn't allow you to provide multiple registrations for a type.
We'll have to change the logic so you can register multiple registrations for a type. At resolution we disambiguate the best one as follows:

Any registrations provided by a module are better than any registrations it defines.

If this doesn't give any best registration we produce an error. The user can solve this by adding a registration for the type to the container, which will be better than any imported registrations. If the container already has multiple registrations for a type, the user will have to move all but one registrations to a module, and import the module.

**Comment by YairHalberstadt** [comment]
@dadhi

Do you think the order is important here as well? Or is it ok to let it be arbitrary but deterministic?

**Comment by dadhi** [comment]
@YairHalberstadt 
Here it is less important, I don't remember it to be a reason for the issue.

Still, the determinism will definitely help - at least to simplify the testing.

Btw, in my Lib the collection items are resolved deterministically in order of registrations (for individual registrations) 
but I do not guarantee the order for the automatic assembly-scan registration (** similar to your case**).

**Comment by YairHalberstadt** [comment]
This is implemented only for arrays for now. Implementing for other collection types will wait on #36 and #40.

**Comment by distantcam** [comment]
Hi!

So now that #36 and #40 are done, is it still worth auto registering types like IEnumerable<T>? It's a little tedious manually creating a factory just to convert T[] => IEnumerable<T> and breaks the magic.

**Comment by YairHalberstadt** [comment]
You can auto register Ienumerable by adding `[RegisterModule(typeof(StandardModule))]`

**Comment by distantcam** [comment]
@YairHalberstadt Thanks! I just realised it was part of CollectionsModule, after I got to the end of the readme. :D
