### ISSUE TITLE
Support Decorators

### ISSUE THREAD

**Issue by YairHalberstadt** [YairHalberstadt/stronginject#39]
A Decorator of `SomeInterface` must must have exactly  one constructor parameter of type `SomeInterface` and must implement `SomeInterface`. Multiple decorators can be registered for a type, and all will be used to wrap the underlying instance.

The order decorators will be applied is an implementation detail. No guarantee as to the order is provided and it may change in the future.

**Comment by dadhi** [comment]
@YairHalberstadt I don't want to intrude, but deterministic ordering seems important, no?

**Comment by YairHalberstadt** [comment]
@dadhi how would you recommend we meaningfully order the decorators? I.e the ordering will happen to be deterministic, if only because StrongInject is deterministic, but should there be a specific order in which they should run, and which is simple for users to understand and reorder?

If not I would suggest to make sure your decorators do not depend on running in a particular order.

**Comment by YairHalberstadt** [comment]
> I don't want to intrude

On the contrary, you're input is highly valued! It's great to have the opinion of someone whose spent far more time working on IOC containers than I have!

**Comment by YairHalberstadt** [comment]
Note that attributes are not considered to be ordered by the CLI spec, so I would prefer not to depend on the order of attributes.

**Comment by dadhi** [comment]
> On the contrary, you're input is highly valued! It's great to have the opinion of someone whose spent far more time working on IOC containers than I have!

Thanks. I wanted to speak because you are formulating the feature similar to what I did and thought 3 years ago. Now I know more. And the most important thing that Decorators (in a wider sense) are super powerful and provide a user-driven customization without introducing ad-hoc features into containers. To name a few - custom initializing and disposing logic.

> If not I would suggest to make sure your decorators do not depend on running in a particular order.

It is not always possible.

> Note that attributes are not considered to be ordered by the CLI spec, so I would prefer not to depend on the order of attributes.

For attributed registrations you may consider adding `int? RelativeOrder` (the name is just an example) attribute property to guarantee the order if `orderA > orderB` and not guarantee the order if property is not set.
I did this myself for the attributed registrations in my lib (which supportedvia MEF based extension).

**Comment by dadhi** [comment]
@YairHalberstadt 

> that Decorators (in a wider sense)

What I mean here and relating to the fact that you  already have a support for factory methods:

- "Decorator" for `A` maybe a constructor of type implementing `A` and accepting the `A` as parameter.
- "Decorator" for `A` maybe a factory method returning `A` and accepting the `A` as parameter. -- "Decorator" constructor or factory metgod may accept other parameters which help to serve the decoration process (configs, services, etc.)
- "Decorator" of `A` does not support decoration of multiple `A` parameters.

Thats it :)
Enabling the unified support for the factory method decorators provides a natural (user-customized) creation pipelines.

Again I don't want want to drive your design, consider this just an info sharing.

**Comment by YairHalberstadt** [comment]
Thanks for the input @dadhi 

I think there's definitely quite a few further things that need to be hashed out: for example how do we order decorators defined in seperate modules? Is this order parameter global? If so it becomes very unwieldy to pick it since you need to know the order of all other decorators to pick your order correctly.

Perhaps it will be enough to say that the order of decorators is only defined within a module. The order of decorators defined in different modules is arbitrary (but deterministic).
