### ISSUE TITLE
Included in reference list

### ISSUE THREAD

**Issue by amis92** [YairHalberstadt/stronginject#64]
Hi,

I've included your repository in my personal [C# Source Generators list](https://github.com/amis92/csharp-source-generators) to help gather these kind of projects in one place and hopefully under single umbrella, thus I propose to add the `csharp-sourcegenerator` topic to this repository to help with visibility.

I hope you're okay with this. If you happen to know other generator projects, I'll be happy to enlist those in my list as well.

Thanks!

**Comment by YairHalberstadt** [comment]
@amis92 that's great! I also know of https://github.com/canton7/RestEase which has started using source generators

**Comment by YairHalberstadt** [comment]
I've added the topic now
