### ISSUE TITLE
Support Microsoft.Extensions.DependencyInjection.Abstractions

### ISSUE THREAD

**Issue by KuraiAndras** [YairHalberstadt/stronginject#69]
It would be nice to be able to use existing infrastructure and just drop in stronginject as a replacement. For example, an existing application might depend on:
- IServiceCollection
- IServiceProvider
- IServiceScope
Implementing these and other related interfaces might make adoption easier and faster

**Comment by YairHalberstadt** [comment]
This is an area I definitely want to explore.

It's not as straightforward as it is for other dependency injectors, as StrongInject is entirely done at compile time, and is fully type checked - there's no build time (so `IServiceCollection` doesn't really make sense), and you can't resolve arbitrary types, only those that you specify at compile time you want to resolve - which makes `IServiceProvider` tricky to do.

I think therefore that it doesn't make much sense for StrongInject to provide implementations of these interfaces. Instead I think we should make it really simple to use StrongInject from a different provider of `Microsoft.Extensions.DependencyInjection`.

I haven't used Asp.NetCore much so I'm still not certain of the best way to do this. Any ideas/contributions would be greatly welcomed!

**Comment by YairHalberstadt** [comment]
I've been experimenting with providing the following set of extension methods on `IServiceCollection`:

```csharp
namespace StrongInject.Extensions.DependencyInjection
{
    public static class IServiceCollectionExtensions
    {
        public static void AddContainerForTransientService<TContainer, TService>(this IServiceCollection services) where TContainer : IContainer<TService> where TService : class;

        public static void AddContainerForTransientService<TService>(this IServiceCollection services, IContainer<TService> container) where TService : class;
        
        public static void AddContainerForScopedService<TContainer, TService>(this IServiceCollection services) where TContainer : IContainer<TService> where TService : class;

        public static void AddContainerForScopedService<TService>(this IServiceCollection services, IContainer<TService> container) where TService : class;

        public static void AddContainerForSingletonService<TContainer, TService>(this IServiceCollection services) where TContainer : IContainer<TService> where TService : class;

        public static void AddContainerForSingletonService<TService>(this IServiceCollection services, IContainer<TService> container) where TService : class;

        public static void AddScopedContainerForTransientService<TContainer, TService>(this IServiceCollection services) where TContainer : IContainer<TService> where TService : class;

        public static void AddScopedContainerForScopedService<TContainer, TService>(this IServiceCollection services) where TContainer : IContainer<TService> where TService : class;
    }
}
```

This will make it really easy to write a Container with StrongInject, and then use it from Microsoft.Extensions.DependencyInjection:

```csharp

var container = new MyContainer();

services.AddContainerForTransientService(container);
```

You can also resolve `IServiceProvider` or anything registered outside the container by passing it into the container as a parameter.

```csharp
public class MyApp
{
	public MyApp(IServiceProvider serviceProvider)...	
}

[Register(typeof(MyApp))]
public class MyContainer : IContainer<MyApp>
{
    [Instance] private readonly IServiceProvider _serviceProvider;
    public MyContainer(IServiceProvider serviceProvider) => _serviceProvider = serviceProvider;
}

services.AddContainerForTransientService<MyContainer, MyApp>();
```

WDYT?

I would love to get feedback on:

Naming
Usability
What else do we need

Before publishing a preview API.

**Comment by YairHalberstadt** [comment]
In order to get disposal to work properly, and to make sure we don't create multiple instances of a Container we'll have to do something like this:

```csharp
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

namespace StrongInject.Extensions.DependencyInjection
{
    public static class IServiceCollectionExtensions
    {
        public static void AddContainerForTransientService<TContainer, TService>(this IServiceCollection services) where TContainer : IContainer<TService> where TService : class
        {
            services.Replace(new ServiceDescriptor(typeof(TContainer), typeof(TContainer), ServiceLifetime.Singleton));
            services.AddTransient<Owned<TService>>(x => x.GetRequiredService<TContainer>().Resolve());
            services.AddTransient<TService>(x => x.GetRequiredService<Owned<TService>>().Value);
        }

        public static void AddContainerForTransientService<TService>(this IServiceCollection services, IContainer<TService> container) where TService : class
        {
            services.AddTransient<Owned<TService>>(x => container.Resolve());
            services.AddTransient<TService>(x => x.GetRequiredService<Owned<TService>>().Value);
        }
    }
}
```

Disposal still wouldn't be as tight as StrongInject usually is (Disposal at the end of each resolution), and will only be disposed at the end of each scope. However Microsoft.Extensions.DependencyInjection can't really do any better than this.

**Comment by YairHalberstadt** [comment]
I've added an experimental package to help you integrate with IServiceCollection. More details [here](https://github.com/YairHalberstadt/stronginject/blob/master/README.md#integrate-with-aspnetcoremicrosoftextensionsdependencyinjection).

Please try it out and let me know what you think!

**Comment by KuraiAndras** [comment]
I'll give it a try tomorrow

**Comment by YairHalberstadt** [comment]
I have now added a sample project at https://github.com/YairHalberstadt/stronginject/tree/master/Samples/AspNetCore
